language: bash
env:
  global:
    - MAINTAINER="Ryan Lieu<github-benzBrake@woai.ru>"
  matrix:
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.34.3
      BUILD_DIRECTORY=server
      TAG_LATEST=true
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.34.3
      BUILD_DIRECTORY=client
      TAG_LATEST=true
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.34.2
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.34.2
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.34.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.34.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.34.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.34.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.33.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.33.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.32.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.32.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.32.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.32.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.31.2
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.31.2
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.31.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.31.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.31.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.31.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.30.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.30.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.29.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.29.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.29.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.29.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.28.2
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.28.2
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.28.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.28.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.28.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.28.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.27.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.27.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.27.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.27.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.26.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.26.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.25.3
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.25.3
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.25.2
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.25.2
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.25.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.25.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.25.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.25.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.24.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.24.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.24.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.24.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.23.3
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.23.3
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.23.2
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.23.2
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.23.1
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.23.1
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.23.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.23.0
      BUILD_DIRECTORY=client
    - DOCKER_REPO=benzbrake/frps
      DOCKER_TAG=v0.22.0
      BUILD_DIRECTORY=server
    - DOCKER_REPO=benzbrake/frpc
      DOCKER_TAG=v0.22.0
      BUILD_DIRECTORY=client

sudo: required
  
services:
  - docker

before_script:
  - chmod +x ./hooks/*.sh

script:
  - if [[ -z ${DOCKER_USERNAME} ]]; then exit 1; fi
  - if [[ -z ${BUILD_DIRECTORY} ]]; then exit 1; fi
  - if [[ -z ${DOCKER_REPO} ]]; then export DOCKER_REPO="${DOCKER_USERNAME}/${BUILD_DIRECTORY}"; fi
  - ./hooks/build.sh

after_success:
  - ./hooks/list.sh
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then ./hooks/upload.sh ; fi

notifications:
  email: false
