name: Buildx
on:
  push:
    branches:
      - "master"
    tags:
      - v*
    paths-ignore:
      - "README.md"
  schedule:
    - cron: 0 0 * * 6

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare For All
        id: prepare
        run: |
          echo "OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo DOCKER_PLATFORMS=linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/arm64/v8,linux/mips64,linux/mips64le,linux/mipsle,linux/mips >> $GITHUB_ENV
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest
          install: true

      - name: Prepare For Frp Client
        id: prepare_client
        run: |
          echo "IMAGE=frpc" >> $GITHUB_ENV

      - name: Build and push For Frp Client
        id: docker_build_client
        uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.VERSION }}
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Image digest For Frp Client
        run: echo ${{ steps.docker_build_client.outputs.digest }}

      - name: Prepare For Frp Server
        id: prepare_server
        run: |
          echo "IMAGE=frps" >> $GITHUB_ENV

      - name: Build and push For Frp Server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          builder: ${{ steps.buildx_server.outputs.name }}
          tags: ${{ env.OWNER }}/${{ env.IMAGE }}:${{ env.VERSION }}
          platforms: ${{ env.DOCKER_PLATFORMS }}

      - name: Image digest For Frp Server
        run: echo ${{ steps.docker_build_server.outputs.digest }}
